- name: Compile backend
  shell: cd /tmp/www/backend && pnpx tsc
  become: yes
  become_user: api

- name: Compile frontend
  shell: cd /tmp/www/backend && pnpm run build
  become: yes
  become_user: spa
