- name: Create base folder with read/write permissions
  shell: mkdir -p /var/www && chmod 777 /var/www

- name: Copy backend
  copy:
    src: ./backend
    dest: /var/www/backend
    owner: api
    mode: '755'

- name: Copy frontend
  copy:
    src: ./frontend
    dest: /var/www/frontend
    owner: spa
    mode: '755'

- name: Copy nginx.conf
  copy:
    src: ./nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: nginx
    mode: '755'
