- name: Kill running api
  shell: killall pnpm

- name: (Re)Start nginx
  service:
    name: nginx
    state: reloaded

- name: Start api
  shell: pnpm server:run
  become: yes
  become_user: api
  chdir: /tmp/www/backend
